import { useState } from "react";
import { Link } from "wouter";
import { Bot, Send, Sparkles, ArrowLeft, Globe2 } from "lucide-react";
import { trpc } from "@/lib/trpc";
import { useLanguage } from "@/contexts/LanguageContext";
import { Button } from "@/components/ui/button";
import { Textarea } from "@/components/ui/textarea";
import { Card, CardContent } from "@/components/ui/card";

export default function AssistantPage() {
  const { lang, toggleLang } = useLanguage(); const [question, setQuestion] = useState(""); const [answer, setAnswer] = useState("");
  const ask = trpc.assistant.ask.useMutation({ onSuccess: data => setAnswer(data.answer) });
  const t = (en: string, ar: string) => lang === "ar" ? ar : en;
  const submit = (e: React.FormEvent) => { e.preventDefault(); if (question.trim()) ask.mutate({ question, language: lang }); };
  const prompts = lang === "ar" ? ["ما هو أفضل ترتيب لمشاهدة Gundam؟", "اقترح أعمالاً تشبه Cowboy Bebop", "ترجم ملخص هذا العمل إلى العربية"] : ["What is the best Gundam watch order?", "Suggest works similar to Cowboy Bebop", "Translate this story summary into Arabic"];
  return <div dir={lang === "ar" ? "rtl" : "ltr"} className="min-h-screen bg-background"><header className="border-b border-border/60"><div className="container flex h-20 items-center justify-between"><Link href="/" className="flex items-center gap-3 font-display text-xl font-bold"><span className="brand-mark"><Bot size={18}/></span>Visual Works</Link><Button variant="ghost" onClick={() => toggleLang()}><Globe2 size={17}/> {lang === "ar" ? "English" : "العربية"}</Button></div></header><main className="container max-w-4xl py-12"><Link href="/" className="mb-10 inline-flex items-center gap-2 text-sm text-muted-foreground hover:text-foreground"><ArrowLeft size={16}/>{t("Back to archive", "العودة إلى الأرشيف")}</Link><div className="mb-10 text-center"><div className="mx-auto mb-5 grid h-16 w-16 place-items-center rounded-2xl bg-primary/15 text-primary"><Sparkles size={28}/></div><p className="eyebrow">ARCHIVE INTELLIGENCE</p><h1 className="section-title">{t("Ask the archive", "اسأل الأرشيف")}</h1><p className="mx-auto mt-4 max-w-xl text-muted-foreground">{t("Research watch orders, compare characters, discover similar works, or translate a summary into Arabic.", "ابحث عن ترتيب المشاهدة، قارن الشخصيات، اكتشف أعمالاً مشابهة، أو ترجم أي ملخص إلى العربية.")}</p></div><div className="mb-8 flex flex-wrap justify-center gap-2">{prompts.map(prompt => <button key={prompt} onClick={() => setQuestion(prompt)} className="rounded-full border border-border px-4 py-2 text-sm text-muted-foreground transition hover:border-primary hover:text-primary">{prompt}</button>)}</div><Card className="border-border/60 shadow-xl"><CardContent className="p-5"><form onSubmit={submit}><Textarea value={question} onChange={e => setQuestion(e.target.value)} placeholder={t("Ask a question about a work, character, unit, or translation...", "اكتب سؤالك عن عمل أو شخصية أو وحدة أو ترجمة...")} className="min-h-32 resize-none border-0 bg-muted/40 text-base focus-visible:ring-primary"/><div className="mt-4 flex justify-end"><Button type="submit" disabled={ask.isPending || !question.trim()} className="rounded-full px-5"><Send size={16}/>{ask.isPending ? t("Thinking...", "جاري التفكير...") : t("Ask assistant", "اسأل المساعد")}</Button></div></form></CardContent></Card>{answer && <Card className="mt-6 border-primary/25 bg-primary/5"><CardContent className="flex gap-4 p-6"><div className="rounded-xl bg-primary/15 p-3 text-primary"><Bot size={20}/></div><div className="prose prose-sm max-w-none dark:prose-invert"><p className="whitespace-pre-wrap leading-7">{answer}</p></div></CardContent></Card>}<p className="mt-8 text-center text-xs text-muted-foreground">{t("AI answers should be checked against cited source material before editorial publication.", "يجب مراجعة إجابات الذكاء الاصطناعي مقابل المصادر قبل نشرها تحريرياً.")}</p></main></div>;
}
